site_name: "Geo Arrêtés"

theme:
  name: "readthedocs"

plugins:
- search
- mkdocstrings:
    handlers:
      python:
        options:
          docstring_style: numpy
          heading_level: 3
          show_source: false
